version: '3.7'

networks:
  dependency-network:
    external:
      name: backend-network

services:

  restonode-order-messaging-service:
    build: .
    networks:
      - dependency-network
    environment:
      - RABBIT_HOST=rabbitmq
      - SENDGRID_API_KEY=WATCH OUT!-REPLACE THIS WITH PROVIDED API KEY!